language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools

    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22

    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

  licenses:
    - 'android-.+'
    - 'android-.+'
    - 'google-.+'