language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-24
    - android-25

    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

  licenses:
    - 'android-.+'
    - 'android-.+'
    - 'google-.+'