language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-25.0.1
    - android-25
    - android-26

    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-25
